version: "2.0"

services:

  front-proxy:
    image: envoyproxy/envoy-alpine
    command: "/usr/local/bin/envoy -c /etc/external-envoy.yaml --service-cluster front-proxy"
    volumes:
    - ./envoy.yaml:/etc/external-envoy.yaml
    networks:
    - front-proxy
    - back
    expose:
    - "80"
    - "8001"
    ports:
    - "80:80"
    - "8001:8001"

  service1:
    build:
      context: ./services/echo
    networks:
    - back
    expose:
    - "8080"
    environment:
      SERVICE_NAME: service1
      PRIVATE_ENDPOINT: http://service1-sidecar:9000

  service1-sidecar:
    image: envoyproxy/envoy-alpine
    command: "/usr/local/bin/envoy -c /etc/external-envoy.yaml --service-cluster echo"
    volumes:
    - ./services/echo/envoy-sidecar.yaml:/etc/external-envoy.yaml
    networks:
    - back
    expose:
    - "80"
    - "9000"

  service2:
    build:
      context: ./services/private
    networks:
    - back
    expose:
    - "8080"

  service2-sidecar:
    image: envoyproxy/envoy-alpine
    command: "/usr/local/bin/envoy -c /etc/external-envoy.yaml --service-cluster private"
    volumes:
    - ./services/private/envoy-sidecar.yaml:/etc/external-envoy.yaml
    networks:
    - back
    expose:
    - "80"

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
    - back
    expose:
    - "9411"
    - "16686"
    ports:
    - "9411:9411"
    - "16686:16686"

networks:
  front-proxy: {}
  back: {}
